import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BreadcrumbNav from "@/components/breadcrumb/crumb";
import Navigation from "@/components/navigations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Navigation/>
          <div className="p-3">
            <BreadcrumbNav/>
            {children}
          </div>
        </div>
        </body>
    </html>
  );
}
